'use client';
import Image from 'next/image';
import { ArrowDownRight, ArrowUpRight, ChevronLeft, ChevronRight, Github, Linkedin, Mail, Maximize2, Menu, Play, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import { certifications, education, experience, nav, projects, skills, social } from '@/data/portfolio';

const LinkArrow=()=> <ArrowUpRight size={18} strokeWidth={1.5}/>;
export default function Portfolio(){
 const root=useRef<HTMLDivElement>(null); const progressRef=useRef<HTMLDivElement>(null); const lenisRef=useRef<Lenis|null>(null); const [menu,setMenu]=useState(false); const [scrolled,setScrolled]=useState(false); const [activeSection,setActiveSection]=useState(''); const [videoOpen,setVideoOpen]=useState<string|null>(null); const [imageOpen,setImageOpen]=useState<string|null>(null); const [slideIndex,setSlideIndex]=useState(0);
 useEffect(()=>{history.scrollRestoration='manual';if(location.hash)history.replaceState(null,'',location.pathname+location.search);scrollTo(0,0);let progressFrame=0;const paintProgress=()=>{progressFrame=0;const value=Math.min(1,Math.max(0,scrollY/(document.documentElement.scrollHeight-innerHeight||1)));if(progressRef.current)progressRef.current.style.transform=`translate3d(0,0,0) scaleX(${value})`;let current='';for(const name of nav){const section=document.getElementById(name.toLowerCase());if(section&&section.getBoundingClientRect().top<=innerHeight*.38)current=name}setActiveSection(current)};const resetScroll=()=>{scrollTo(0,0);setActiveSection('');if(progressRef.current)progressRef.current.style.transform='translate3d(0,0,0) scaleX(0)'};addEventListener('pageshow',resetScroll);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches; const onScroll=()=>{setScrolled(scrollY>32);if(!progressFrame)progressFrame=requestAnimationFrame(paintProgress)}; addEventListener('scroll',onScroll,{passive:true});paintProgress(); if(reduce)return()=>{removeEventListener('scroll',onScroll);removeEventListener('pageshow',resetScroll);cancelAnimationFrame(progressFrame)};
 gsap.registerPlugin(ScrollTrigger); const lenis=new Lenis({duration:1.1,smoothWheel:true});lenisRef.current=lenis; let rafId=0; const raf=(t:number)=>{lenis.raf(t);rafId=requestAnimationFrame(raf)};rafId=requestAnimationFrame(raf);
 const ctx=gsap.context(()=>{gsap.from('.hero-line > span',{yPercent:110,duration:1.15,stagger:.12,ease:'power4.out'});gsap.from('.hero-meta',{opacity:0,y:24,duration:.8,delay:.65,stagger:.08});gsap.utils.toArray<HTMLElement>('[data-reveal]').forEach(el=>gsap.from(el,{opacity:0,y:55,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 86%'}}));gsap.utils.toArray<HTMLElement>('.project-visual:not(.slideshow)').forEach(el=>{const image=el.querySelector('img');if(image)gsap.fromTo(image,{scale:1.08},{scale:1,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:true}})});},root);
 return()=>{removeEventListener('scroll',onScroll);removeEventListener('pageshow',resetScroll);cancelAnimationFrame(progressFrame);cancelAnimationFrame(rafId);lenisRef.current=null;lenis.destroy();ctx.revert()};},[]);
 const go=(id:string)=>{setMenu(false);const target=document.getElementById(id.toLowerCase());if(!target)return;if(lenisRef.current){lenisRef.current.scrollTo(target,{offset:id==='top'?0:-64,duration:1.25})}else{target.scrollIntoView({behavior:'smooth'})}};
 useEffect(()=>{if(!videoOpen&&!imageOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setVideoOpen(null);setImageOpen(null)}};document.body.style.overflow='hidden';addEventListener('keydown',close);return()=>{document.body.style.overflow='';removeEventListener('keydown',close)}},[videoOpen,imageOpen]);
 return <div ref={root}>
   <div ref={progressRef} className="progress"/>
  <header className={scrolled?'nav nav-scrolled':'nav'}><a href="#top" className="wordmark" onClick={e=>{e.preventDefault();go('top')}}>SIBTAIN AHMED</a><nav>{nav.map(n=><button className={activeSection===n?'active':''} aria-current={activeSection===n?'page':undefined} key={n} onClick={()=>go(n)}>{n}</button>)}<a className="resume-nav" href="/Sibtain-Ahmed-Resume.pdf" target="_blank" rel="noreferrer" aria-label="View Sibtain Ahmed's résumé in a new tab">View Résumé ↗</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header>
  {menu&&<div className="mobile-nav">{nav.map((n,i)=><button className={activeSection===n?'active':''} aria-current={activeSection===n?'page':undefined} key={n} onClick={()=>go(n)}><span>0{i+1}</span>{n}</button>)}<a className="mobile-resume" href="/Sibtain-Ahmed-Resume.pdf" target="_blank" rel="noreferrer"><span>PDF</span>View Résumé ↗</a></div>}
  <main>
   <section className="hero" id="top"><div className="hero-orbit"/><p className="eyebrow hero-meta">PORTFOLIO / 2026</p><div className="hero-name"><h1 className="hero-line"><span>SIBTAIN</span></h1><h1 className="hero-line outline"><span>AHMED</span></h1><p className="hero-location hero-meta">Karachi, Pakistan</p></div><div className="hero-bottom"><div><p className="role hero-meta">SOFTWARE ENGINEER</p><p className="hero-facts hero-meta"><span>SQA Intern at 1LINK (Pvt) Limited</span></p><p className="statement hero-meta">I build software, explore systems, and turn ideas into digital experiences.</p></div><div className="hero-actions hero-meta"><a href="#projects" onClick={e=>{e.preventDefault();go('projects')}} className="button primary">Explore my work <ArrowDownRight/></a><a href="#contact" onClick={e=>{e.preventDefault();go('contact')}} className="button">Contact me <LinkArrow/></a></div></div><div className="hero-social hero-meta"><a href={social.github} target="_blank" rel="noreferrer" aria-label="GitHub" data-label="GitHub"><Github/></a><a href={social.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" data-label="LinkedIn"><Linkedin/></a><a href={social.email} aria-label="Email Sibtain Ahmed" data-label="sibtain.ahmed19@gmail.com"><Mail/></a></div><span className="scroll-label">SCROLL TO DISCOVER</span></section>
   <section id="about" className="section about"><p className="section-index">01 / ABOUT</p><div className="about-grid"><h2 data-reveal>ABOUT ME</h2><div data-reveal><p className="lead">I enjoy building useful software and understanding how it works behind the scenes.</p><p>Through university projects and my SQA internship at 1LINK (Pvt) Limited, I’m gaining practical experience in development, API testing, and quality assurance.</p></div></div></section>
   <section id="experience" className="section experience"><div className="section-head"><p className="section-index">02 / EXPERIENCE</p><h2 data-reveal>EXPERIENCE</h2></div><div className="experience-panel" data-reveal><div className="experience-top"><div><span className="live-dot"/> CURRENT ROLE</div><span>{experience.period}</span></div><div className="experience-main"><div><h3>{experience.company}</h3><p>{experience.role}</p><small>{experience.team}<br/>{experience.location}</small></div><p className="experience-copy">{experience.summary}</p></div><div className="exposure"><p>AREAS OF EXPOSURE</p><div>{experience.areas.map(x=><span key={x}>{x}</span>)}</div></div></div></section>
   <section id="projects" className="projects section"><p className="section-index">03 / PROJECTS</p><h2 className="projects-title" data-reveal>PROJECTS</h2>{projects.map((p,i)=><article className={`project project-${p.tone}`} key={p.name}><div className="project-copy" data-reveal><span className="project-number">/{p.number}</span><h3>{p.name}</h3><p>{p.description}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><div className="tech">{p.tech.map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><a href={p.github} target="_blank" rel="noreferrer">View project <LinkArrow/></a><a href={p.github} target="_blank" rel="noreferrer">GitHub <Github size={17}/></a></div></div>{p.video?<button className="project-visual video-preview" onClick={()=>setVideoOpen(p.video)} aria-label={`Play ${p.name} demo`}><video muted loop autoPlay playsInline preload="metadata" poster="/images/project-showcase.png"><source src={p.video} type="video/mp4"/></video><span className="play-badge"><Play size={15} fill="currentColor"/> WATCH DEMO</span></button>:p.images?<div className="project-visual slideshow" role="region" aria-label={`${p.name} screenshots`}>{p.images.map((image,index)=><Image key={image} className={`slide-image ${index===slideIndex?'active':''}`} src={image} alt={`${p.name} screenshot ${index+1} of ${p.images.length}`} fill sizes="(max-width: 900px) 100vw, 60vw" priority/>)}<button className="slide-arrow prev" onClick={()=>setSlideIndex((slideIndex-1+p.images!.length)%p.images!.length)} aria-label="Previous screenshot"><ChevronLeft/></button><button className="slide-arrow next" onClick={()=>setSlideIndex((slideIndex+1)%p.images!.length)} aria-label="Next screenshot"><ChevronRight/></button><button className="slide-expand" onClick={()=>setImageOpen(p.images![slideIndex])} aria-label="View screenshot fullscreen"><Maximize2/></button><div className="slide-dots">{p.images.map((image,index)=><button key={image} className={index===slideIndex?'active':''} onClick={()=>setSlideIndex(index)} aria-label={`View screenshot ${index+1}`}/>)}</div><span className="slide-count">{String(slideIndex+1).padStart(2,'0')} / {String(p.images.length).padStart(2,'0')}</span></div>:<a className="project-visual" href={p.github} target="_blank" rel="noreferrer" aria-label={`Open ${p.name} on GitHub`}><Image src="/images/project-showcase.png" alt={`${p.name} conceptual interface artwork`} fill sizes="(max-width: 900px) 100vw, 60vw" style={{objectPosition:p.imagePosition}} priority={i===0}/><span>VIEW ON GITHUB ↗</span></a>}</article>)}</section>
   <section id="skills" className="section skills"><p className="section-index">04 / SKILLS</p><div className="skills-head"><h2 data-reveal>SKILLS &<br/><em>TECHNOLOGIES</em></h2><p data-reveal>Development, testing, and delivery.</p></div><div className="skill-list">{skills.map((s,i)=><div className="skill-row" data-reveal key={s.group}><span>0{i+1}</span><h3>{s.group}</h3><div>{s.items.map(x=><p key={x}>{x}</p>)}</div></div>)}</div></section>
   <section id="education" className="section education"><p className="section-index">05 / EDUCATION</p><h2 data-reveal>EDUCATION</h2><div className="timeline">{education.map((e,i)=><article data-reveal key={e.degree}><span className="timeline-no">0{i+1}</span><div><h3>{e.degree}</h3><p>{e.school}</p></div><div><p>{e.period}</p><small>{e.location}</small></div></article>)}</div></section>
   <section id="certifications" className="section certs"><p className="section-index">06 / CERTIFICATIONS</p><div className="cert-head"><h2 data-reveal>CERTIFICATIONS</h2><p>Courses and professional credentials.</p></div><div className="cert-list">{certifications.map(c=><a href={c.url} target="_blank" rel="noreferrer" className="cert" key={c.name} data-reveal><span>{c.number}</span><h3>{c.name}</h3><p>{c.issuer}</p><span className="credential">VIEW CREDENTIAL <LinkArrow/></span></a>)}</div></section>
   <section id="contact" className="contact"><p className="section-index">07 / CONTACT</p><h2 data-reveal>CONTACT</h2><div className="contact-bottom"><p>Open to learning, collaboration, and software engineering opportunities.</p><div className="contact-links"><a href={social.email}>Email <LinkArrow/></a><a href={social.whatsapp} target="_blank" rel="noreferrer" title="WhatsApp: +92 318 3489210">WhatsApp <LinkArrow/></a><a href={social.linkedin} target="_blank" rel="noreferrer">LinkedIn <LinkArrow/></a><a href={social.github} target="_blank" rel="noreferrer">GitHub <LinkArrow/></a></div></div><footer><span>© {new Date().getFullYear()} SIBTAIN AHMED</span><span>KARACHI, PAKISTAN</span><a href="#top" onClick={e=>{e.preventDefault();go('top')}}>BACK TO TOP ↑</a></footer></section>
  </main>
  {videoOpen&&<div className="video-modal" role="dialog" aria-modal="true" aria-label="Project demonstration video" onMouseDown={e=>{if(e.target===e.currentTarget)setVideoOpen(null)}}><button className="video-close" onClick={()=>setVideoOpen(null)} aria-label="Close video"><X/></button><div className="video-frame"><video src={videoOpen} controls autoPlay playsInline preload="auto"/></div></div>}
  {imageOpen&&<div className="image-modal" role="dialog" aria-modal="true" aria-label="Project screenshot" onMouseDown={e=>{if(e.target===e.currentTarget)setImageOpen(null)}}><button className="video-close" onClick={()=>setImageOpen(null)} aria-label="Close image"><X/></button><div className="image-frame"><Image src={imageOpen} alt="Student Management System enlarged screenshot" fill sizes="95vw"/></div></div>}
 </div>
}
